# Generated by Django 5.2.1 on 2025-06-26 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0002_initial'),
        ('mypage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_member', '새 멤버'), ('new_promise', '새 약속'), ('vote_complete', '투표 완료'), ('place_selected', '장소 선택'), ('photo_comment', '사진 댓글')], max_length=30)),
                ('message', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mypage.createcommunity')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community.photo')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
