# Generated by Django 5.2.1 on 2025-06-26 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notification', '0001_initial'),
        ('promise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='promise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='promise.promise'),
        ),
    ]
