# Generated by Django 5.2.1 on 2025-05-26 01:53

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateCommunity',
            fields=[
                ('communityname', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('createuser', models.CharField(max_length=100)),
                ('communityintro', models.TextField()),
                ('communityimage', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=90, scale=None, size=[500, 500], upload_to='mypage/mypage_image/')),
            ],
        ),
    ]
