# Generated by Django 5.2.1 on 2025-06-17 14:54

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateCommunity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('community_name', models.CharField(max_length=100, unique=True)),
                ('create_user', models.CharField(max_length=100)),
                ('community_intro', models.TextField()),
                ('community_image', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=90, scale=None, size=[500, 500], upload_to='mypage/mypage_image/')),
            ],
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '대기중'), ('accepted', '수락됨'), ('rejected', '거절됨')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
