# Generated by Django 5.2.1 on 2025-05-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0002_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='createcommunity',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='createcommunity',
            name='communityname',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='CommunityMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communityname', models.CharField(max_length=100)),
                ('createuser', models.CharField(max_length=100)),
                ('member', models.CharField(max_length=100)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('communityname', 'member')},
            },
        ),
    ]
