# Generated by Django 5.2.1 on 2025-05-30 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0002_communityinvite'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='communityinvite',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='communityinvite',
            name='community',
        ),
        migrations.RemoveField(
            model_name='communityinvite',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='communityinvite',
            name='to_user',
        ),
        migrations.DeleteModel(
            name='CommunityMember',
        ),
        migrations.DeleteModel(
            name='CommunityInvite',
        ),
    ]
