# Generated by Django 5.2.1 on 2025-06-16 11:12

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createcommunity',
            name='community_image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=90, scale=None, size=[500, 500], upload_to='mypage/mypage_image/'),
        ),
    ]
