# Generated by Django 5.2.1 on 2025-06-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='communitymember',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='communitymember',
            name='community_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
