# Generated by Django 5.2.1 on 2025-06-12 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0001_initial'),
        ('mypage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityinvite',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mypage.createcommunity'),
        ),
    ]
