# Generated by Django 5.2.1 on 2025-06-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_communitymember_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='communitymember',
            unique_together={('community_name', 'member')},
        ),
        migrations.AddField(
            model_name='communitymember',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='communitymember',
            name='community_name',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='communitymember',
            name='joined_at',
        ),
    ]
