# Generated by Django 5.2.1 on 2025-06-17 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communitymember',
            old_name='community',
            new_name='community_name',
        ),
    ]
