# Generated by Django 5.2.1 on 2025-06-12 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='communitymember',
            unique_together=set(),
        ),
    ]
