# Generated by Django 5.2.1 on 2025-06-19 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_communitycolorsetting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommunityColorSetting',
        ),
    ]
