# Generated by Django 5.2.1 on 2025-06-24 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_delete_communitycolorsetting'),
        ('mypage', '0003_communitycolor'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mypage.createcommunity')),
            ],
        ),
    ]
