# Generated by Django 5.2.1 on 2025-05-27 07:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promise', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='promisevote',
            unique_together={('username', 'promise', 'selected_date')},
        ),
    ]
