# Generated by Django 5.2.1 on 2025-05-26 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromiseVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('promise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promise.promise')),
            ],
        ),
    ]
