# Generated by Django 5.2.1 on 2025-05-30 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promise', '0002_promise_promise_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promise',
            name='promise_creator',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
