# Generated by Django 5.2.1 on 2025-05-30 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promise', '0003_alter_promise_promise_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promisevote',
            name='promise',
            field=models.CharField(max_length=100),
        ),
    ]
