# Generated by Django 5.2.1 on 2025-05-30 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promise', '0004_alter_promisevote_promise'),
    ]

    operations = [
        migrations.AddField(
            model_name='promisevote',
            name='promise_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='promisevote',
            name='promise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promise.promise'),
        ),
    ]
