# Generated by Django 5.2.1 on 2025-05-30 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promise', '0005_promisevote_promise_name_alter_promisevote_promise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promise',
            name='promise_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='PromiseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promise_name', models.CharField(max_length=100, null=True)),
                ('promise_creator', models.CharField(max_length=100, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('place', models.CharField(blank=True, max_length=255, null=True)),
                ('promise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promise.promise')),
            ],
        ),
    ]
