# Generated by Django 5.2.1 on 2025-06-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promise', '0006_alter_promise_promise_name_promiseresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promiseresult',
            name='place',
        ),
        migrations.AddField(
            model_name='promiseresult',
            name='center_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promiseresult',
            name='center_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
