# Generated by Django 5.2.1 on 2025-06-04 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promise', '0007_remove_promiseresult_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promiseresult',
            name='places_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
