# Generated by Django 5.2.1 on 2025-06-19 12:07

import django_resized.forms
import user_account.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default=user_account.models.get_random_default_image, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[500, 500], upload_to='profile/'),
        ),
    ]
